dist: xenial
sudo: required

language: python
python: 3.7

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.62.2/hugo_0.62.2_Linux-64bit.deb
  - sudo dpkg -i hugo_0.62.2_Linux-64bit.deb

  - pip install markdata

script:
  # Python tests:
  - cd code/py
  - pip install -r requirements.txt
  - pytest test.py
  - cd -

  # Node.js tests:
  - cd code/js
  - npm install
  - ./node_modules/mocha/bin/mocha
  - cd -

after_success:
  # Build our content:
  - markdata --root . docs content/post

  # Build our site:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
